AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
    
Resources:
  RetirementReadinessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Timeout: 7
      Runtime: nodejs8.10
      CodeUri: ./lambda/custom/
      Events:
        AlexaTrigger:
          Type: AlexaSkill

Outputs:
  RetirementReadinessFunctionArn:
    Value: !GetAtt RetirementReadinessFunction.Arn
    Export: {
      Name: !Sub '${AWS::StackName}:RetirementReadinessFunction:Arn'
      }